global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'

receivers:
- name: 'email-alerts'
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
    subject: '🚨 SITE DOWN: {{ .GroupLabels.alertname }}'
    body: |
      ALERT: Your website is DOWN!
      
      Site: {{ range .Alerts }}{{ .Labels.instance }}{{ end }}
      Status: {{ range .Alerts }}{{ .Status }}{{ end }}
      Time: {{ range .Alerts }}{{ .StartsAt }}{{ end }}
      
      Please check your website immediately.