global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'azure-app-service'
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: 
        - lexicon-server-eddeced3fzf3czaw.canadaeast-01.azurewebsites.net # Upadeted target endpoint

  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'azure-app-service-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://lexicon-server-eddeced3fzf3czaw.canadaeast-01.azurewebsites.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115