global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
alertmanagers:
  - static_configs:
      - targets:
        - 'alertmanager:9093'

#collectors
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-expoter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'azure-monitor'
    static_configs:
      - targets: ['azure-exporter:9276']